// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmLOwoeJm1MZqs-fZCrz6kovuRw1F2EpA',
    appId: '1:470252396245:web:fbf032b59098f3596d8c5c',
    messagingSenderId: '470252396245',
    projectId: 'spoonfood-f9729',
    authDomain: 'spoonfood-f9729.firebaseapp.com',
    storageBucket: 'spoonfood-f9729.firebasestorage.app',
    measurementId: 'G-ZW6B59DK91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm5bb7FbFW4NoZnPVBKdrPRmdJLqsQ8nQ',
    appId: '1:470252396245:android:1bcd844c864863c66d8c5c',
    messagingSenderId: '470252396245',
    projectId: 'spoonfood-f9729',
    storageBucket: 'spoonfood-f9729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC45U7B8x8Nmz-NGFgheFQONhYMjBH59N8',
    appId: '1:470252396245:ios:e2ede90516cf9c206d8c5c',
    messagingSenderId: '470252396245',
    projectId: 'spoonfood-f9729',
    storageBucket: 'spoonfood-f9729.firebasestorage.app',
    iosClientId: '470252396245-uimuh9rsfdf019enbsj7pv44fe0rul7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.spoonfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC45U7B8x8Nmz-NGFgheFQONhYMjBH59N8',
    appId: '1:470252396245:ios:e2ede90516cf9c206d8c5c',
    messagingSenderId: '470252396245',
    projectId: 'spoonfood-f9729',
    storageBucket: 'spoonfood-f9729.firebasestorage.app',
    iosClientId: '470252396245-uimuh9rsfdf019enbsj7pv44fe0rul7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.spoonfood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmLOwoeJm1MZqs-fZCrz6kovuRw1F2EpA',
    appId: '1:470252396245:web:2db8aec87fbf34f56d8c5c',
    messagingSenderId: '470252396245',
    projectId: 'spoonfood-f9729',
    authDomain: 'spoonfood-f9729.firebaseapp.com',
    storageBucket: 'spoonfood-f9729.firebasestorage.app',
    measurementId: 'G-EFP4E5CW1R',
  );
}
